
name: CI/CD Demo

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clone source code
      uses: actions/checkout@v3

    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: 📦 Cài đặt dependencies
      run: npm install

    - name: 🧪 Chạy kiểm tra (test)
      run: npm test

    - name: 🚀 Triển khai lên Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "ten-app-heroku-cua-ban"
        heroku_email: "email-cua-ban@example.com"
